# fly.toml app configuration file generated for langflow-nginx-auth on 2025-05-19T05:18:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'langflow-nginx-auth'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 4096
